package com.satrango.ui.service_provider.provider_dashboard.provider_dashboard.my_bids.models

data class JobPostDetailX(
    val amount: Int,
    val average_bids_amount: String,
    val bid_end_date: String,
    val bid_per: String,
    val bid_range_name: String,
    val bids_period: String,
    val booking_id: String,
    val booking_status: String,
    val current_date: String,
    val distance_miles: String,
    val estimate_time: String,
    val estimate_type: String,
    val expires_in: String,
    val fcm_token: String,
    val fname: String,
    val from: String,
    val job_post_description: List<JobPostDescription>,
    val lname: String,
    val mobile: String,
    val post_created_on: String,
    val post_job_id: String,
    val post_job_ref_id: String,
    val range_slots: String,
    val scheduled_date: String,
    val sp_id: String,
    val started_at: String,
    val title: String,
    val total_bids: Int
)