package com.satrango.utils

object Constants {

    // Colors

    const val white = "#FFFFFF"
    const val black = "#000000"


    // Strings

    const val completed = "Completed"
    const val inProgress = "InProgress"
    const val pending = "Pending"
    const val expired = "Expired"
    const val cancelled = "Cancelled"
    const val sp_capital = "SP"
    const val datetime_format = "yyyy-MM-dd hh:mm"
    const val invalid_otp = "Invalid OTP"
    const val booking_started = "Booking Started!"
    const val otp_to_start_job = "OTP to Start Job"
    const val enter_expenditure_incurred = "Enter Expenditure Incurred"
    const val message = "message"
    const val otp = "otp"
    const val status = "status"
    const val status_camil = "Status"
    const val success_small = "success"
    const val success_camil = "Success"
    const val plan_id = "Plan Id:"
    const val freedom = "Freedom"
    const val activation = "Activation:"
    const val activation_date_time = "Activation Date and Time"
    const val valid_till = "Valid till:"
    const val completed_at_date = "Completed At Date"
    const val unknown = "unknown"
    const val please_check_internet_connection = "Please check internet connection!"
    const val user = "User"
    const val accept = "accept"
    const val booking_accepted = "Booking Accepted Successfully"
    const val are_you_sure_to_logout = "Are you sure to logout?"
    const val yes_capital = "YES"
    const val something_went_wrong = "Something went wrong. Please try again"
    const val no_capital = "NO"
    const val close = "Close"
    const val not_approved = "Not Approved"
    const val sp_banned = "Your Service Provider Account has been Banned!"
    const val login_time_out = "Login Session Timeout"
    const val server_busy = "Server Busy"
    const val alert = "Alert"
    const val ok_capital = "Ok"
    const val no_permission = "No permission"
    const val yes_camil = "Yes"
    const val resume = "Resume"
    const val pause = "Pause"
    const val mark_complete = "Mark Complete"
    const val extra_demand_raised = "Extra Demand Raised"
    const val extra_demand_accepted = "EXTRA DEMAND ACCEPTED"
    const val extra_demand_rejected = "EXTRA DEMAND REJECTED"
    const val final_expenditure_alert = "Final Expenditure is more than extra demanded from user"
    const val enter_material_charges_alert = "Enter Material Charges or Technician Charges"
    const val extra_demand_waiting_alert = "Please wait until User respond to Latest Extra Demand Raised by You."
    const val mark_complete_alert = "Please Ask the Service Provider to click on Mark Complete to get Booking Invoice"
    const val otp_success = "OTP Verification Success"
    const val single_move = "Single Move"
    const val phone_no_alert = "Please Enter Valid 10 digit Mobile Number"
    const val password_alert = "Please Enter Password"
    const val login = "login"

}